version: '{build}'
image: Visual Studio 2015
platform:
- x64
- x86
environment:
  global:
    DISTUTILS_USE_SDK: 1
    MSSdk: 1
  matrix:
  - PYTHON: 27
  - PYTHON: 35
  - PYTHON: 36
  - PYTHON: 37
  pypipassword:
    # https://ci.appveyor.com/tools/encrypt
    #secure: GRzEKTz0q+eRwEFvm1Vdrg==
    secure: gAr0Sm5HnS179dcErNLElw==
install:
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
- cmd: git reset --hard
- ps: Remove-Item -Recurse -Force C:/cygwin
- ps: Remove-Item -Recurse -Force C:/cygwin64
- ps: |
    if ($env:PYTHON) {
      if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
      $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
      python -m pip install --disable-pip-version-check --upgrade pip
      python -m pip install -qq setuptools Cython
    } elseif ($env:CONDA) {
      if ($env:CONDA -eq "27") { $env:CONDA = "" }
      if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
      $env:PATH = "C:\Miniconda$env:CONDA\;C:\Miniconda$env:CONDA\Scripts\;$env:PATH"
      conda config --set always_yes yes --set changeps1 no
      conda config --add channels conda-forge
      conda update -q conda
      conda install -q conda-build
    }
- cmd: |
    python --version
    python -m pip --version
build_script:
- ps: cd cpp
- cmd: |
    python -m pip install -U .
- ps: cd ..

test_script:
- ps: cd cpp
- cmd: |
    python -m pip install -U .[test]
    python setup.py test
- ps: cd ..

deploy_script: 
- ps: |
    if ($env:APPVEYOR_REPO_TAG -ne "true") {
      echo "Skipping deployment because this is not a tagged commit"
      return
    }
    echo "Deploying..."
    # Specify account details for PyPI
    mv .pypirc $env:USERPROFILE\\.pypirc
    # ensure README gets packaged
    mv README.md cpp
    # Workaround required to ensure setup.py finds the .pypirc under Windows
    $env:HOME=$env:USERPROFILE
    # Install wheel-building support
    python -m pip install --user wheel twine
    # Build wheel and upload
    cd cpp
    python setup.py sdist bdist_wheel
    python -m twine upload -r pypi -p $env:pypipassword --skip-existing dist/*
    echo "Deployment complete"

