package:
    name: s_gd2
    version: 0
    
source:
    path: ../
    
requirements:
    build:
        - python
        - numpy
        - setuptools
    run:
        - python
        - networkx
        - numpy
        - scipy 
