name: Publish Python 🐍 distributions 📦 to PyPI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true
      matrix:
        config:
        - {name: 'windows-3.8-x64', os: windows-latest, python: '3.8', architecture: 'x64' }
        - {name: 'windows-3.8-x86', os: windows-latest, python: '3.8', architecture: 'x86' }
        - {name: 'windows-3.9-x64', os: windows-latest, python: '3.9', architecture: 'x64' }
        - {name: 'windows-3.9-x86', os: windows-latest, python: '3.9', architecture: 'x86' }

    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}
        architecture: ${{ matrix.config.architecture }}

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{runner.os}}-pip-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
        restore-keys: ${{runner.os}}-pip-${{ env.pythonLocation }}-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U wheel setuptools build Cython

    - name: Build a binary wheel and a source tarball
      run: |
        python -m build --sdist --wheel --outdir dist/ .

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
