name: Unit Tests

on:
  push:
    branches-ignore:
      - 'test_deploy'
  pull_request:
    branches:
      - '*'

jobs:
  run_linter:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'current', os: ubuntu-latest, python: '3.8' }


    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}

    - name: Install tools
      run: |
        python -m pip install --upgrade pip
        pip install -U wheel setuptools
        pip install -U black flake8

    - name: Lint with Black
      run: |
        cd cpp
        black . --check --diff

    - name: Lint with flake8
      run: |
        flake8 s_gd2 || true

  run_tester:
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-10.15, macos-11.0]
        python-version: ['2.7', '3.5', '3.6', '3.7', '3.8', '3.9']
        architecture: [x64, x86]
        exclude:
          - os: ubuntu-latest
            architecture: x86
          - os: macos-10.15
            architecture: x86
          - os: macos-11.0
            architecture: x86

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.architecture }}

    - name: Cache Python packages
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{runner.os}}-pip-${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}
        restore-keys: ${{runner.os}}-pip-${{ env.pythonLocation }}-

    - name: Install package & dependencies
      run: |
        cd cpp
        python -m pip install --upgrade pip
        pip install -U wheel setuptools
        pip install -U .[test]
        python -c "import s_gd2"

    - name: Run tests
      run: |
        cd test
        nose2 -v test_mds

    - name: Upload check results on fail
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.config.name }}_results
        path: check
